# Generated by Django 5.2.1 on 2025-05-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status_payment",
            field=models.CharField(
                choices=[("paid", "Оплачен"), ("not_paid", "Не оплачен")],
                default="not_paid",
                max_length=10,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
